Indicators/urls.py
from django.conf.urls import url
from django.contrib import admin
import Indicators_app.views
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    url(
        r"^indicators/", include("Indicators_app.urls")
    ),
    url(r"^admin/", admin.site.urls),
    url(r"^general_info/$", Indicators_app.views.general_info, name="general_info"),
    url(r"^landing/$", Indicators_app.views.landing, name="landing"),
    url(r"^wash/$", Indicators_app.views.wash, name="wash"),
    url(r"^login/$", auth_views.LoginView.as_view(), name="login"),
    url(
        r"^logout/$", auth_views.LogoutView.as_view(), {"next_page": "/"}, name="logout"
    ),
    url(r"^$", Indicators_app.views.home, name="home"),
]

Indicators_app/urls.py
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views

app_name = 'indicators'

router = routers.DefaultRouter()
router.register(r'section', api.SectionViewSet)
router.register(r'indicator', api.IndicatorViewSet)
router.register(r'periode', api.PeriodeViewSet)
router.register(r'output', api.OutputViewSet)
router.register(r'indicatorsectionperiode', api.IndicatorSectionPeriodeViewSet)
router.register(r'partner', api.PartnerViewSet)
router.register(r'report', api.ReportViewSet)
router.register(r'involvedpartner', api.InvolvedPartnerViewSet)
router.register(r'concernedreport', api.ConcernedReportViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Section
    path('Indicators_app/section/', views.SectionListView.as_view(), name='Indicators_app_section_list'),
    path('Indicators_app/section/create/', views.SectionCreateView.as_view(), name='Indicators_app_section_create'),
    path('Indicators_app/section/detail/<int:pk>/', views.SectionDetailView.as_view(), name='Indicators_app_section_detail'),
    path('Indicators_app/section/update/<int:pk>/', views.SectionUpdateView.as_view(), name='Indicators_app_section_update'),
)

urlpatterns += (
    # urls for Indicator
    path('Indicators_app/indicator/', views.IndicatorListView.as_view(), name='Indicators_app_indicator_list'),
    path('Indicators_app/indicator/create/', views.IndicatorCreateView.as_view(), name='Indicators_app_indicator_create'),
    path('Indicators_app/indicator/detail/<int:pk>/', views.IndicatorDetailView.as_view(), name='Indicators_app_indicator_detail'),
    path('Indicators_app/indicator/update/<int:pk>/', views.IndicatorUpdateView.as_view(), name='Indicators_app_indicator_update'),
)

urlpatterns += (
    # urls for Periode
    path('Indicators_app/periode/', views.PeriodeListView.as_view(), name='Indicators_app_periode_list'),
    path('Indicators_app/periode/create/', views.PeriodeCreateView.as_view(), name='Indicators_app_periode_create'),
    path('Indicators_app/periode/detail/<int:pk>/', views.PeriodeDetailView.as_view(), name='Indicators_app_periode_detail'),
    path('Indicators_app/periode/update/<int:pk>/', views.PeriodeUpdateView.as_view(), name='Indicators_app_periode_update'),
)

urlpatterns += (
    # urls for Output
    path('Indicators_app/output/', views.OutputListView.as_view(), name='Indicators_app_output_list'),
    path('Indicators_app/output/create/', views.OutputCreateView.as_view(), name='Indicators_app_output_create'),
    path('Indicators_app/output/detail/<int:pk>/', views.OutputDetailView.as_view(), name='Indicators_app_output_detail'),
    path('Indicators_app/output/update/<int:pk>/', views.OutputUpdateView.as_view(), name='Indicators_app_output_update'),
)

urlpatterns += (
    # urls for IndicatorSectionPeriode
    path('Indicators_app/indicatorsectionperiode/', views.IndicatorSectionPeriodeListView.as_view(), name='Indicators_app_indicatorsectionperiode_list'),
    path('Indicators_app/indicatorsectionperiode/create/', views.IndicatorSectionPeriodeCreateView.as_view(), name='Indicators_app_indicatorsectionperiode_create'),
    path('Indicators_app/indicatorsectionperiode/detail/<int:pk>/', views.IndicatorSectionPeriodeDetailView.as_view(), name='Indicators_app_indicatorsectionperiode_detail'),
    path('Indicators_app/indicatorsectionperiode/update/<int:pk>/', views.IndicatorSectionPeriodeUpdateView.as_view(), name='Indicators_app_indicatorsectionperiode_update'),
)

urlpatterns += (
    # urls for Partner
    path('Indicators_app/partner/', views.PartnerListView.as_view(), name='Indicators_app_partner_list'),
    path('Indicators_app/partner/create/', views.PartnerCreateView.as_view(), name='Indicators_app_partner_create'),
    path('Indicators_app/partner/detail/<int:pk>/', views.PartnerDetailView.as_view(), name='Indicators_app_partner_detail'),
    path('Indicators_app/partner/update/<int:pk>/', views.PartnerUpdateView.as_view(), name='Indicators_app_partner_update'),
)

urlpatterns += (
    # urls for Report
    path('Indicators_app/report/', views.ReportListView.as_view(), name='Indicators_app_report_list'),
    path('Indicators_app/report/create/', views.ReportCreateView.as_view(), name='Indicators_app_report_create'),
    path('Indicators_app/report/detail/<int:pk>/', views.ReportDetailView.as_view(), name='Indicators_app_report_detail'),
    path('Indicators_app/report/update/<int:pk>/', views.ReportUpdateView.as_view(), name='Indicators_app_report_update'),
)

urlpatterns += (
    # urls for InvolvedPartner
    path('Indicators_app/involvedpartner/', views.InvolvedPartnerListView.as_view(), name='Indicators_app_involvedpartner_list'),
    path('Indicators_app/involvedpartner/create/', views.InvolvedPartnerCreateView.as_view(), name='Indicators_app_involvedpartner_create'),
    path('Indicators_app/involvedpartner/detail/<int:pk>/', views.InvolvedPartnerDetailView.as_view(), name='Indicators_app_involvedpartner_detail'),
    path('Indicators_app/involvedpartner/update/<int:pk>/', views.InvolvedPartnerUpdateView.as_view(), name='Indicators_app_involvedpartner_update'),
)

urlpatterns += (
    # urls for ConcernedReport
    path('Indicators_app/concernedreport/', views.ConcernedReportListView.as_view(), name='Indicators_app_concernedreport_list'),
    path('Indicators_app/concernedreport/create/', views.ConcernedReportCreateView.as_view(), name='Indicators_app_concernedreport_create'),
    path('Indicators_app/concernedreport/detail/<int:pk>/', views.ConcernedReportDetailView.as_view(), name='Indicators_app_concernedreport_detail'),
    path('Indicators_app/concernedreport/update/<int:pk>/', views.ConcernedReportUpdateView.as_view(), name='Indicators_app_concernedreport_update'),
)

Indicators_app/forms.py
from django import forms
from .models import Section, Indicator, Periode, Output, IndicatorSectionPeriode, Partner, Report, InvolvedPartner, ConcernedReport


class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = ['section_designation']


class IndicatorForm(forms.ModelForm):
    class Meta:
        model = Indicator
        fields = ['indicator_designation']


class PeriodeForm(forms.ModelForm):
    class Meta:
        model = Periode
        fields = ['periode_designation']


class OutputForm(forms.ModelForm):
    class Meta:
        model = Output
        fields = ['output_designation', 'output_description']


class IndicatorSectionPeriodeForm(forms.ModelForm):
    class Meta:
        model = IndicatorSectionPeriode
        fields = ['target_value', 'value', 'section', 'indicator', 'periode', 'output']


class PartnerForm(forms.ModelForm):
    class Meta:
        model = Partner
        fields = ['partner_designation']


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['report_designation']


class InvolvedPartnerForm(forms.ModelForm):
    class Meta:
        model = InvolvedPartner
        fields = ['results', 'indicator', 'partner']


class ConcernedReportForm(forms.ModelForm):
    class Meta:
        model = ConcernedReport
        fields = ['indicator', 'report']

Indicators_app/views.py
from django.shortcuts import render
from Indicators_app.models import *
from django.contrib.auth.decorators import login_required
from django.db.models import F
import json
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .forms import *
from django_filters.rest_framework import DjangoFilterBackend


class SectionListView(ListView):
    model = Section


class SectionCreateView(CreateView):
    model = Section
    form_class = SectionForm


class SectionDetailView(DetailView):
    model = Section


class SectionUpdateView(UpdateView):
    model = Section
    form_class = SectionForm


class IndicatorListView(ListView):
    model = Indicator


class IndicatorCreateView(CreateView):
    model = Indicator
    form_class = IndicatorForm


class IndicatorDetailView(DetailView):
    model = Indicator


class IndicatorUpdateView(UpdateView):
    model = Indicator
    form_class = IndicatorForm


class PeriodeListView(ListView):
    model = Periode


class PeriodeCreateView(CreateView):
    model = Periode
    form_class = PeriodeForm


class PeriodeDetailView(DetailView):
    model = Periode


class PeriodeUpdateView(UpdateView):
    model = Periode
    form_class = PeriodeForm


class OutputListView(ListView):
    model = Output


class OutputCreateView(CreateView):
    model = Output
    form_class = OutputForm


class OutputDetailView(DetailView):
    model = Output


class OutputUpdateView(UpdateView):
    model = Output
    form_class = OutputForm


class IndicatorSectionPeriodeListView(ListView):
    model = IndicatorSectionPeriode
    filter_backends = (DjangoFilterBackend,)
    filterset_fields = ('indicator', 'section')


class IndicatorSectionPeriodeCreateView(CreateView):
    model = IndicatorSectionPeriode
    form_class = IndicatorSectionPeriodeForm


class IndicatorSectionPeriodeDetailView(DetailView):
    model = IndicatorSectionPeriode


class IndicatorSectionPeriodeUpdateView(UpdateView):
    model = IndicatorSectionPeriode
    form_class = IndicatorSectionPeriodeForm


class PartnerListView(ListView):
    model = Partner


class PartnerCreateView(CreateView):
    model = Partner
    form_class = PartnerForm


class PartnerDetailView(DetailView):
    model = Partner


class PartnerUpdateView(UpdateView):
    model = Partner
    form_class = PartnerForm


class ReportListView(ListView):
    model = Report


class ReportCreateView(CreateView):
    model = Report
    form_class = ReportForm


class ReportDetailView(DetailView):
    model = Report


class ReportUpdateView(UpdateView):
    model = Report
    form_class = ReportForm


class InvolvedPartnerListView(ListView):
    model = InvolvedPartner


class InvolvedPartnerCreateView(CreateView):
    model = InvolvedPartner
    form_class = InvolvedPartnerForm


class InvolvedPartnerDetailView(DetailView):
    model = InvolvedPartner


class InvolvedPartnerUpdateView(UpdateView):
    model = InvolvedPartner
    form_class = InvolvedPartnerForm


class ConcernedReportListView(ListView):
    model = ConcernedReport


class ConcernedReportCreateView(CreateView):
    model = ConcernedReport
    form_class = ConcernedReportForm


class ConcernedReportDetailView(DetailView):
    model = ConcernedReport


class ConcernedReportUpdateView(UpdateView):
    model = ConcernedReport
    form_class = ConcernedReportForm



def date_handler(obj):
    if hasattr(obj, "isoformat"):
        return obj.isoformat()
    else:
        raise TypeError


def landing(request):
    return render(request, "landing_page.html")


def home(request):
    d = dict()
    d["pagetitle"] = "Choose Sections"
    d["sections"] = Section.objects.all()
    return render(request, "home.html", d)


def wash(request):
    d = dict()
    d["pagetitle"] = "Choose Sections"
    return render(request, "wash.html", d)



@login_required
def general_info(request):
    d = {}
    d["pagetitle"] = "General informations"

    general_indicators_informations = (
        IndicatorSectionPeriode.objects.all()
        .annotate(periode_designation=F("periode__periode_designation"))
        .annotate(section_designation=F("section__section_designation"))
        .annotate(indicator_designation=F("indicator__indicator_designation"))
        .annotate(output_designation=F("output__output_designation"))
        .values()
    )

    for indi in general_indicators_informations:
        related_reports = (
            ConcernedReport.objects.filter(indicator=indi["id"])
            .annotate(report_designation=F("report__report_designation"))
            .values()
        )
        reports_list = []
        if len(related_reports) > 0:
            first_report = True
            for r in related_reports:
                one_report_name = ""
                if first_report:
                    one_report_name = r["report_designation"]
                else:
                    one_report_name = ", " + r["report_designation"]
                reports_list.append(one_report_name)
        indi["related_reports"] = reports_list

        related_partners = (
            InvolvedPartner.objects.filter(indicator=indi["id"])
            .annotate(partner_name=F("partner__partner_designation"))
            .values()
        )
        partner_list = []
        if len(related_partners) > 0:
            first_partner = True
            for p in related_partners:
                one_partner_name = ""
                if first_partner:
                    one_partner_name = p["partner_name"]
                else:
                    one_partner_name = ", " + p["partner_name"]
                partner_list.append(one_partner_name)
        indi["related_partners"] = partner_list

    rows = json.dumps(list(general_indicators_informations), default=date_handler)

    return render(request, "general_info.html", {"rows": rows})

templates/Indicators_app/concernedreport_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_concernedreport_list' %}">ConcernedReport Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/Indicators_app/indicator_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_indicator_list' %}">Indicator Listing</a></p>
<table class="table">
<tr><td>indicator_designation</td><td>{{ object.indicator_designation }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Indicator</a>

{% endblock %}

templates/Indicators_app/indicator_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_indicator_list' %}">Indicator Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>indicator_designation</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.indicator_designation }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'indicators:Indicators_app_indicator_create' %}">Create new Indicator</a>
{% endblock %}

templates/Indicators_app/indicatorsectionperiode_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_indicatorsectionperiode_list' %}">IndicatorSectionPeriode Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/Indicators_app/involvedpartner_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_involvedpartner_list' %}">InvolvedPartner Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/Indicators_app/involvedpartner_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_involvedpartner_list' %}">InvolvedPartner Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>results</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.results }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'indicators:Indicators_app_involvedpartner_create' %}">Create new InvolvedPartner</a>
{% endblock %}

templates/Indicators_app/output_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_output_list' %}">Output Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/Indicators_app/partner_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_partner_list' %}">Partner Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/Indicators_app/periode_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_periode_list' %}">Periode Listing</a></p>
<table class="table">
<tr><td>periode_designation</td><td>{{ object.periode_designation }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Periode</a>

{% endblock %}

templates/Indicators_app/periode_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_periode_list' %}">Periode Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/Indicators_app/periode_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_periode_list' %}">Periode Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>periode_designation</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.periode_designation }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'indicators:Indicators_app_periode_create' %}">Create new Periode</a>
{% endblock %}

templates/Indicators_app/section_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row">
    <div>
    <a class="btn btn-default" href="{% url 'indicators:Indicators_app_section_list' %}">Section Listing
    </a>
    <a class="btn btn-primary" href="{{object.get_update_url}}">Edit Section</a>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <td>Section Designation</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{{ object.section_designation }}</td>
        </tr>
    </tbody>
</table>

<div class="row">
        <div class="col-sm-12">
            <table id="albums" class="table table-striped table-bordered" >
                  <thead>
                    <tr>
                        <th >ID</th>
                        <th >Periode</th>
                        <th >Output</th>
                        <th >Indicator</th>
                        <th >Target Value</th>
                        <th >Current Value </th>
                        <th >Section</th>
                        <th >Partners</th>
                    </tr>
                  </thead>
            </table>
        </div>
    </div>
</div>
<script>
  $(document).ready(function() {
      $('#albums').DataTable(
        {
            ajax: {
                url: "{% url "indicators:indicatorsectionperiode-list" %}?format=datatables&section={{object.id}}",
            },
            columns: [
                  {'data': 'pk'},
                  {'data': 'periode',  'name': 'periode.periode_designation'},
                  {'data': 'output',  'name': 'output.output_designation, output.output_description'},
                  {'data': 'indicator',  'name': 'indicator.indicator_designation'},
                  {'data': 'target_value'},
                  {'data': 'value'},
                  {'data': 'section',  'name': 'section.section_designation'},
                  {'data': 'partner',  'name': 'partner'}
              ],
            dom: "<'row'<'col-sm-3'l><'col-sm-4'i><'col-sm-5'f>>" +
                "<'row'<'col-sm-12'tr>>" +
                "<'row'<'col-sm-4'B><'col-sm-8'p>>",
            pagingType: "full_numbers",
            lengthMenu: [
                [10, 25, 50, 100, -1 ],
                ['10', '25', '50', '100', 'All' ]
            ],
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]

        }
        );
  });
</script>


{% endblock %}

templates/Indicators_app/section_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_section_list' %}">Section Listing</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/Indicators_app/section_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'indicators:Indicators_app_section_list' %}">Section Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>section_designation</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
    <td>{{ object.section_designation }}</td>
</tr>
{% endfor %}
</table><a class="btn btn-primary" href="{% url 'indicators:Indicators_app_section_create' %}">Create new Section</a>
{% endblock %}