Indicators/urls.py
from django.conf.urls import url
from django.contrib import admin
import Indicators_app.views
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    url(
        r"^indicators/", include("Indicators_app.urls")
    ),
    url(r"^admin/", admin.site.urls),
    url(r"^general_info/$", Indicators_app.views.general_info, name="general_info"),
    url(r"^landing/$", Indicators_app.views.landing, name="landing"),
    url(r"^wash/$", Indicators_app.views.wash, name="wash"),
    url(r"^login/$", auth_views.LoginView.as_view(), name="login"),
    url(
        r"^logout/$", auth_views.LogoutView.as_view(), {"next_page": "/"}, name="logout"
    ),
    url(r"^$", Indicators_app.views.home, name="home"),
]

Indicators_app/urls.py
from django.urls import path, include
from rest_framework import routers

from . import api
from . import views

app_name = 'indicators'

router = routers.DefaultRouter()
router.register(r'section', api.SectionViewSet)
router.register(r'indicator', api.IndicatorViewSet)
router.register(r'periode', api.PeriodeViewSet)
router.register(r'output', api.OutputViewSet)
router.register(r'indicatorsectionperiode', api.IndicatorSectionPeriodeViewSet)
router.register(r'partner', api.PartnerViewSet)
router.register(r'report', api.ReportViewSet)
router.register(r'involvedpartner', api.InvolvedPartnerViewSet)
router.register(r'concernedreport', api.ConcernedReportViewSet)


urlpatterns = (
    # urls for Django Rest Framework API
    path('api/v1/', include(router.urls)),
)

urlpatterns += (
    # urls for Section
    path('Indicators_app/section/', views.SectionListView.as_view(), name='Indicators_app_section_list'),
    path('Indicators_app/section/create/', views.SectionCreateView.as_view(), name='Indicators_app_section_create'),
    path('Indicators_app/section/detail/<int:pk>/', views.SectionDetailView.as_view(), name='Indicators_app_section_detail'),
    path('Indicators_app/section/update/<int:pk>/', views.SectionUpdateView.as_view(), name='Indicators_app_section_update'),
)

urlpatterns += (
    # urls for Indicator
    path('Indicators_app/indicator/', views.IndicatorListView.as_view(), name='Indicators_app_indicator_list'),
    path('Indicators_app/indicator/create/', views.IndicatorCreateView.as_view(), name='Indicators_app_indicator_create'),
    path('Indicators_app/indicator/detail/<int:pk>/', views.IndicatorDetailView.as_view(), name='Indicators_app_indicator_detail'),
    path('Indicators_app/indicator/update/<int:pk>/', views.IndicatorUpdateView.as_view(), name='Indicators_app_indicator_update'),
)

urlpatterns += (
    # urls for Periode
    path('Indicators_app/periode/', views.PeriodeListView.as_view(), name='Indicators_app_periode_list'),
    path('Indicators_app/periode/create/', views.PeriodeCreateView.as_view(), name='Indicators_app_periode_create'),
    path('Indicators_app/periode/detail/<int:pk>/', views.PeriodeDetailView.as_view(), name='Indicators_app_periode_detail'),
    path('Indicators_app/periode/update/<int:pk>/', views.PeriodeUpdateView.as_view(), name='Indicators_app_periode_update'),
)

urlpatterns += (
    # urls for Output
    path('Indicators_app/output/', views.OutputListView.as_view(), name='Indicators_app_output_list'),
    path('Indicators_app/output/create/', views.OutputCreateView.as_view(), name='Indicators_app_output_create'),
    path('Indicators_app/output/detail/<int:pk>/', views.OutputDetailView.as_view(), name='Indicators_app_output_detail'),
    path('Indicators_app/output/update/<int:pk>/', views.OutputUpdateView.as_view(), name='Indicators_app_output_update'),
)

urlpatterns += (
    # urls for IndicatorSectionPeriode
    path('Indicators_app/indicatorsectionperiode/', views.IndicatorSectionPeriodeListView.as_view(), name='Indicators_app_indicatorsectionperiode_list'),
    path('Indicators_app/indicatorsectionperiode/create/', views.IndicatorSectionPeriodeCreateView.as_view(), name='Indicators_app_indicatorsectionperiode_create'),
    path('Indicators_app/indicatorsectionperiode/detail/<int:pk>/', views.IndicatorSectionPeriodeDetailView.as_view(), name='Indicators_app_indicatorsectionperiode_detail'),
    path('Indicators_app/indicatorsectionperiode/update/<int:pk>/', views.IndicatorSectionPeriodeUpdateView.as_view(), name='Indicators_app_indicatorsectionperiode_update'),
)

urlpatterns += (
    # urls for Partner
    path('Indicators_app/partner/', views.PartnerListView.as_view(), name='Indicators_app_partner_list'),
    path('Indicators_app/partner/create/', views.PartnerCreateView.as_view(), name='Indicators_app_partner_create'),
    path('Indicators_app/partner/detail/<int:pk>/', views.PartnerDetailView.as_view(), name='Indicators_app_partner_detail'),
    path('Indicators_app/partner/update/<int:pk>/', views.PartnerUpdateView.as_view(), name='Indicators_app_partner_update'),
)

urlpatterns += (
    # urls for Report
    path('Indicators_app/report/', views.ReportListView.as_view(), name='Indicators_app_report_list'),
    path('Indicators_app/report/create/', views.ReportCreateView.as_view(), name='Indicators_app_report_create'),
    path('Indicators_app/report/detail/<int:pk>/', views.ReportDetailView.as_view(), name='Indicators_app_report_detail'),
    path('Indicators_app/report/update/<int:pk>/', views.ReportUpdateView.as_view(), name='Indicators_app_report_update'),
)

urlpatterns += (
    # urls for InvolvedPartner
    path('Indicators_app/involvedpartner/', views.InvolvedPartnerListView.as_view(), name='Indicators_app_involvedpartner_list'),
    path('Indicators_app/involvedpartner/create/', views.InvolvedPartnerCreateView.as_view(), name='Indicators_app_involvedpartner_create'),
    path('Indicators_app/involvedpartner/detail/<int:pk>/', views.InvolvedPartnerDetailView.as_view(), name='Indicators_app_involvedpartner_detail'),
    path('Indicators_app/involvedpartner/update/<int:pk>/', views.InvolvedPartnerUpdateView.as_view(), name='Indicators_app_involvedpartner_update'),
)

urlpatterns += (
    # urls for ConcernedReport
    path('Indicators_app/concernedreport/', views.ConcernedReportListView.as_view(), name='Indicators_app_concernedreport_list'),
    path('Indicators_app/concernedreport/create/', views.ConcernedReportCreateView.as_view(), name='Indicators_app_concernedreport_create'),
    path('Indicators_app/concernedreport/detail/<int:pk>/', views.ConcernedReportDetailView.as_view(), name='Indicators_app_concernedreport_detail'),
    path('Indicators_app/concernedreport/update/<int:pk>/', views.ConcernedReportUpdateView.as_view(), name='Indicators_app_concernedreport_update'),
)

templates/base-default.html
{% load i18n %}
{% load staticfiles %}

<!doctype html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		
		<title>UNICEF BURUNDI | {% if pagetitle %} | {{ pagetitle }}{% endif %}</title>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oxygen:300">
		
		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

		<!-- Local css-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/css/font-awesome.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'js/Messi-master/messi.min.css' %}">
		
		<!-- Local js -->
		<script type="text/javascript" src="{% static 'js/Messi-master/messi.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/moment.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/spin.js' %}"></script>

		{% block head %}
		
		{% endblock %}
		
		<script language="JavaScript">
			$(document).ready(function() {
				
				$("input:submit, a.button").button();
				{% if notification %}
					showNotification("{{ notification }}");
				{% endif %}
				
				/*if (!window.jQuery) {
					messiprompt({% trans "Your internet connection is not reliable. Computations not possible." %}, {% trans "Internet Connection" %}, "messierror");
					return;
				}*/
			});
			
		
			function messiprompt(msg, title, titleanimation) {
				var titleclass;

				if (titleanimation == "messisuccess") {
					titleclass = 'success';

				} else if (titleanimation == "messiinfo") {
					titleclass = 'info';

				} else if (titleanimation == "messiwarning") {
					titleclass = 'anim warning';

				} else if (titleanimation == "messierror") {
					titleclass = 'anim error';
				}

				new Messi(msg, { title: title, titleClass: titleclass, modal: true });
			}
			
			
		</script>
	</head>
	
	<body class="offsetfootermargin" {% block bodytag %}{% endblock %}>
		{% block header %}
			<div class="fitcontent" class="container" style="width:100%; padding: 0px">
				<nav class="navbar navbar-default" style="width:100%;">
					<div class="container-fluid" style="width:100%;">
						<div class="navbar-header" style="width:100%;">
							<button class="navbar-toggle collapsed" aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button">
								<span class="sr-only">{% trans "Toggle navigation" %}</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						
						<div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="width:100%; padding-top:10px;">
							<ul class="nav navbar-nav navbar" style="width:100%">
								<h1 class="bet-logo">
									<a href="/">
										<div class="col-sm-1" style="padding-left:5px; padding-right:5px;">
											
										</div>
										<div class="col-sm-8 verticallineseparator" style="padding-left:5px; padding-right:5px;">
											<span class="brand-app" style="text-align:center;">Indicators</span>
											
										</div>
										<div class="col-sm-1" >
											<img class="noborder size-full aligncenter" src="{% static 'images/burundi.png' %}" scale="0">
										</div>
										{% if user.is_authenticated %}
										<div class="col-sm-1" >
												<li><a role="button" href="{% url 'home' %}">{% trans "Home" %}</a></li>
										</div>
										<div class="col-sm-1" >
												<li><a role="button" href="/logout">{% trans "Logout" %}</a></li>
										</div>
											{% else %}
												<li><a role="button" href="/login">{% trans "Login" %}</a></li>
											{% endif %}
										</div>
									</a>
								</h1>
							</ul>
						</div>
					</div>
				</nav>
			</div>
		{% endblock %}
		
		
		{% block content %}
		

		{% endblock %}
			<!--</div>
		</div>-->
		
		{% block footer %}
			<div class="fitcontent" id="footer-widgets" class="footer-widgets">
				<div class="wrap">
					<div class="row">
						<div class="col-sm-4" style="overflow:auto;">
							<div class="footer-widgets-2 widget-area">
								<div class="widget-wrap">
									<p style="text-align: center;">
										<img class="noborder size-full aligncenter" src="{% static 'images/moh1.jpg' %}" scale="0">
									</p>
								</div>
							</div>
						</div>

						<div class="col-sm-4" style="overflow:auto;">
							<div class="footer-widgets-1 widget-area">
								<div class="widget">
									<div class="widget-wrap">
										<p class="copyright text-muted small" style="text-align: center;">
											© 2017
												{% trans "Unicef Burundi" %}
										</p>
									</div>
								</div>
							</div>
						</div>
						
						<div class="col-sm-4" style="overflow:auto;">
							<div class="footer-widgets-2 widget-area">
								<div class="widget-wrap">
									<p style="text-align: center;">
										<img class="noborder size-full aligncenter" src="{% static 'images/unicef-cyan-logo1.png' %}" scale="0">
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>

templates/base.html
{% load i18n %}
{% load staticfiles %}

<!doctype html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="csrf_token" content="{{ csrf_token }}">
		
		<title>UNICEF BURUNDI | {% if pagetitle %} | {{ pagetitle }}{% endif %}</title>
		{% block jqueries %}
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">	
		{% endblock jqueries %}
		<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oxygen:300">

		<script src="http://code.highcharts.com/highcharts.js"></script>
		<script src="http://code.highcharts.com/highcharts-more.js"></script>
		<script src="http://code.highcharts.com/modules/exporting.js"></script>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

		{% block datatables %}
		<!-- dataTable CSS-->
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/dataTables.bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.0.1/css/responsive.bootstrap.min.css">
		
		<!-- dataTable JS -->
		<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
		<script src="https://cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>
		<script src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
		<script src="https://cdn.datatables.net/responsive/2.0.1/js/dataTables.responsive.min.js"></script>
		<script src="https://cdn.datatables.net/responsive/2.0.1/js/responsive.bootstrap.min.js"></script>
		<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.bootstrap.min.js"></script>
		<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.flash.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
		<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
		<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
		<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.html5.min.js"></script>
		<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.print.min.js"></script>	
		{% endblock datatables %}

		<!-- Local css -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/css/font-awesome.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'js/Messi-master/messi.min.css' %}">
		
		<!-- Local js -->
		<script type="text/javascript" src="{% static 'js/Messi-master/messi.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/moment.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/spin.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/sonic.js-master/src/sonic.js' %}"></script>

		{% block head %}
		
		{% endblock %}
	</head>
	
	<body class="offsetfootermargin" {% block bodytag %}{% endblock %} >
		{% block header %}
		<nav class="navbar navbar-inverse">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span> 
		      </button>
		      <a class="navbar-brand" href="/">Indicators</a>
		    </div>
		    <div class="collapse navbar-collapse" id="myNavbar">
		      <ul class="nav navbar-nav">
		        <li class="active"><a href="/">Home</a></li>
		        <li><a href="{% url "general_info" %}">General Info</a></li>
		        <li><a href="{% url "general_info" %}">Choose section</a></li> 
		      </ul>
		      <ul class="nav navbar-nav navbar-right">
		      	{% if user.is_authenticated %}
		        <li><a href="{% url "logout" %}"><span class="glyphicon glyphicon-user"></span> Logout</a></li>
		        {% else %}
		        <li><a href="{% url "login" %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
		        {% endif %}
		      </ul>
		    </div>
		  </div>
		</nav>
		{% endblock %}
		
		{% if user.is_authenticated %}
			{% block navbar %}
				<div role="presentation" class="fitcontent" id="nav">
					
				</div>
			{% endblock %}
		{% endif %}
		
		<div class="fitcontent" id="divmain" class="container-fluid">
			<div id="divinnermain" class="container-fluid">
				{% block content %}
					
		
				{% endblock %}
			</div>
		</div>
		
		{% block footer %}
			<div class="fitcontent" id="footer-widgets" class="footer-widgets">
				<div class="wrap">
					<div class="row">
						<div class="col-sm-4" style="overflow:auto;">
							<div class="footer-widgets-2 widget-area">
								<div class="widget-wrap">
									<p style="text-align: center;">
										
									</p>
								</div>
							</div>
						</div>

						<div class="col-sm-4" style="overflow:auto;">
							<div class="footer-widgets-1 widget-area">
								<div class="widget">
									<div class="widget-wrap">
										<p style="text-align: center;">
											©2019 Unicef Burundi
										</p>
									</div>
								</div>
							</div>
						</div>
						
						<div class="col-sm-4" style="overflow:auto;">
							<div class="footer-widgets-2 widget-area">
								<div class="widget-wrap">
									<p style="text-align: center;">
										<img class="noborder size-full aligncenter" src="{% static 'images/unicef-cyan-logo1.png' %}" scale="0">
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		{% endblock %}
	</body>
</html>

templates/general_info.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
	<title> {{ pagetitle }}</title>
{% endblock %}

{% block pagename %}pagename{% endblock %}

{% block head %}
	<script language="JavaScript">
		var messimsg;
		var messititle;
		var titleanimation;
		
		$(document).ready(function() {
			if ((".divmessage").length) {
				$(".divmessage").fadeIn('slow').animate({opacity: 1.0}, 1500).effect("pulsate", { times: 2 }, 800).fadeOut('slow'); 
			}
			
			if ((".diverror").length) {
				$(".diverror").fadeIn('slow').animate({opacity: 1.0}, 1500).effect("pulsate", { times: 2 }, 800); 
			}
		
		displayActiveCHWDetails();

		});



		function displayActiveCHWDetails(){
			$('#div_general_info').append('<p><b></b></p>' +

								'<div style="clear:both; height:10px;"></div>' +

								'<table id="tblgnrlinfo" class="table table-striped table-bordered table-condensed">');
								
								$('#tblgnrlinfo').append('<thead>' +
									'<th>{% trans "Periode" %}</th><th>{% trans "Section" %}</th><th>{% trans "Indicator" %}</th><th>{% trans "Output" %}</th><th>{% trans "Target" %}</th><th>{% trans "Value" %}</th><th>{% trans "Partner" %}</th><th>{% trans "Report" %}</th>' +
								'</thead>' +
									
								'<tbody>' +
									
								'</tbody>');

								

			var general_info = "{{rows|escapejs}}";
			var table_data = JSON.parse(general_info);

			console.log(table_data);

			var periode, section, output, indicator, target, value;

			for(i=0; i<table_data.length; i++){

				periode = table_data[i]["periode_designation"];
				section = table_data[i]["section_designation"];
				indicator = table_data[i]["indicator_designation"];
				output = table_data[i]["output_designation"];
				target = table_data[i]["target_value"];
				value = table_data[i]["value"];
				partner = table_data[i]["related_partners"];
				report = table_data[i]["related_reports"];

				$('#tblgnrlinfo').find('tbody').append('<tr style="cursor:pointer;"></tr>');

				$('#tblgnrlinfo tr:last').append('<td>' + periode +'</td>');
				$('#tblgnrlinfo tr:last').append('<td>' + section +'</td>');
				$('#tblgnrlinfo tr:last').append('<td>' + indicator +'</td>');
				$('#tblgnrlinfo tr:last').append('<td>' + output +'</td>');
				$('#tblgnrlinfo tr:last').append('<td>' + target +'</td>');
				$('#tblgnrlinfo tr:last').append('<td>' + value +'</td>');
				$('#tblgnrlinfo tr:last').append('<td>' + partner +'</td>');
				$('#tblgnrlinfo tr:last').append('<td>' + report +'</td>');
			}

			$('#tblgnrlinfo').DataTable({
										dom: "<'row'<'col-sm-3'l><'col-sm-4'i><'col-sm-5'f>>" +
											"<'row'<'col-sm-12'tr>>" +
											"<'row'<'col-sm-4'B><'col-sm-8'p>>",
										pagingType: "full_numbers",
										lengthMenu: [
								            [10, 25, 50, 100, -1 ],
								            ['10', '25', '50', '100', 'All' ]
								        ],
								        buttons: [
								            'copy', 'csv', 'excel', 'pdf', 'print'
								        ]
									});


		}
	</script>
{% endblock %}



{% block content %}
	<div>
		{% if msg %}
			<div class="divmessage"><p>{{ msg }}</p></div>
		{% endif %}
		{% if err %}
			<div class="diverror"><p>{{ err }}</p></div>
		{% endif %}

		<div id="div_general_info" class="form-inline" style="padding-left :5px; padding-right :5px;">
		<p><b>
		</b></p>

		<!--{{data}}-->

		</div>

	</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
	<title> {{ pagetitle }}</title>
{% endblock %}

{% block pagename %}Home{% endblock %}

{% block head %}
<style>
  .thumbnail {
   box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.5);
   transition: 0.3s;
   min-width: 40%;
   border-radius: 5px;
  }

  .thumbnail-description {
   min-height: 40px;
  }

  .thumbnail:hover {
   cursor: pointer;
   box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 1);
  }
</style>

{% endblock %}



{% block content %}
{% if user.is_authenticated %}
<div class="row">
  {% for section in sections  %}
      <div class="col-sm-2">
        <div class="thumbnail">
          <div class="caption text-center" onclick="location.href='{% url "indicators:Indicators_app_section_detail" pk=section.id %}'">
            <div class="position-relative">
              <img src="https://via.placeholder.com/72"/>
            </div>
            <h4 id="thumbnail-label">
              <a href="{% url "indicators:Indicators_app_section_detail" pk=section.id %}" target="_blank">
                {{section}}
              </a>
            </h4>
          </div>
        </div>
      </div>
    {% endfor %}  
</div>
{% endif %}
{% endblock %}

templates/landing_page.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
	<title> {{ pagetitle }}</title>
{% endblock %}

{% block pagename %}pagename{% endblock %}

{% block head %}
	<script language="JavaScript">
		var messimsg;
		var messititle;
		var titleanimation;
		
		$(document).ready(function() {
			if ((".divmessage").length) {
				$(".divmessage").fadeIn('slow').animate({opacity: 1.0}, 1500).effect("pulsate", { times: 2 }, 800).fadeOut('slow'); 
			}
			
			if ((".diverror").length) {
				$(".diverror").fadeIn('slow').animate({opacity: 1.0}, 1500).effect("pulsate", { times: 2 }, 800); 
			}
		});
		
	</script>
{% endblock %}


{% block content %}
	<div>
		{% if msg %}
			<div class="divmessage"><p>{{ msg }}</p></div>
		{% endif %}
		{% if err %}
			<div class="diverror"><p>{{ err }}</p></div>
		{% endif %}
	</div>
	
	<div>
		<div class="content-wrapper" style="background-color: #1ce7ea; padding: 30px; border: solid; height: 450px;">
			<div class="row">
				<div class="col-sm-4">
					<div class="">
		                
		            </div>
				</div>
				<div class="col-sm-8">
					<!--<div class="rounded_2">-->
					
		            <!--</div>-->
				</div>
				<!--<div class="col-sm-4">
					
				</div>-->
			</div>

			<div class="row" style="background-color: #1ce7ea; padding-top: 10px;">
				<div class="col-sm-2">
					
				</div>
				<div class="col-sm-8">
				</div>
				<div class="col-sm-2">
					
				</div>
			</div>

		</div>
	</div>
{% endblock %}

templates/wash.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
	<title> WASH</title>
{% endblock %}

{% block pagename %}WASH{% endblock %}

{% block head %}

{% endblock %}



{% block content %}
{% if user.is_authenticated %}
  <div class="row">
    Infos wash
  </div>
{% endif %}
{% endblock %}